### ISSUE TITLE
Archive this project

### ISSUE THREAD

**Issue by cstamas** [codehaus-plexus/plexus-build-api#33]
Am really unsure who on earth thought it is "good idea" to revive this dead project in the first place. Please archive it, as this just raises that already huge confusion around maven and "incremental build" support.

**Comment by olamy** [comment]
this project is still used by https://github.com/eclipse-m2e/m2e-core which is very active project
So at least by courtesy we should propose some remplacement for m2e.
Even if I'm not an Eclipse user, I think this project is used a lot...

**Comment by kwin** [comment]
It is used by all Maven plugins natively supporting m2e (https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html), compare also with the discussion from https://lists.apache.org/thread/h2gy5l7j5bv7ycbpwdjby66v8gwhzck2.

**Comment by laeubi** [comment]
https://mvnrepository.com/artifact/org.sonatype.plexus/plexus-build-api/0.0.7/usages and many of that usages has recent release so its far from being "dead" in contrast to the approaches to provide a "better" alternative maven official API :-(

**Comment by laeubi** [comment]
I think this one can be closed for now?
